name: flutter_avif_android
description: Android implementation for flutter_avif.
version: 2.0.1
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_android

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      android:
        package: com.teknorota.flutter_avif
        pluginClass: FlutterAvifPlugin
        dartPluginClass: FlutterAvifAndroid
